#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="ghostty,git,nvim,pacman,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

# Install stow
sudo pacman -S --needed stow

# Run stow
STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

# Install packages
sudo pacman -S --needed yay
yay -S --needed - < ~/pkglist.txt

# Link ~/.oh-my-zsh
[[ ! -e ~/.oh-my-zsh ]] && ln -s /usr/share/oh-my-zsh ~/.oh-my-zsh
